import 'dart:math';
import 'package:instagram/models/post.dart';
import 'package:instagram/models/story.dart';
import 'package:instagram/models/user.dart';
import 'package:faker/faker.dart';

final fakerFa = Faker(provider: FakerDataProviderFa());

User currentUser = User(
  userName: "flash",
  name: "barry allen",
  status: "Nothing to say really",
  followersCount: 1000,
  followingCount: 100,
  isLive: false,
  isStoryActive: false,
  isVerified: true,
  posts: <Post>[],
  postsCount: 499,
  profileImage: "assets/images/story29.jpg",
);

List<User> users = [
  User(
    userName: "trivia",
    name: "reflect me",
    status: "Nothing to say really",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story1.jpg",
  ),
  User(
    userName: "superman",
    name: "kent",
    status: "Nothing to say really",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story2.jpg",
  ),
  User(
    userName: "hulk",
    name: "banner",
    status: "always angry",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story3.jpg",
  ),
  User(
    userName: "Johnny",
    name: "Depp",
    status: "Nothing to say really",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story4.jpg",
  ),
  User(
    userName: "Surya",
    name: "Depp",
    status: "Nothing to say really",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story5.jpg",
  ),
  User(
    userName: "iron",
    name: "man",
    status: "Nothing to say really",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story6.jpg",
  ),
  User(
    userName: "vortex",
    name: "english",
    status: "Nothing to say really",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story7.jpg",
  ),
  User(
    userName: "spidey",
    name: "peter parker",
    status: "Nothing to say really",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story8.jpg",
  ),
  User(
    userName: "natalie",
    name: "portman",
    status: "Nothing to say really",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story9.jpg",
  ),
  User(
    userName: "scarlett",
    name: "widow",
    status: "Nothing to say really",
    followersCount: 1000,
    followingCount: 100,
    isLive: false,
    isStoryActive: true,
    isVerified: true,
    posts: <Post>[],
    postsCount: 499,
    profileImage: "assets/images/story9.jpg",
  ),
];

List<Story> stories = [
  Story(
    isClose: false,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
  Story(
    isClose: false,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
  Story(
    isClose: false,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
  Story(
    isClose: false,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
  Story(
    isClose: false,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
  Story(
    isClose: true,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
  Story(
    isClose: false,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
  Story(
    isClose: false,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
  Story(
    isClose: true,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
  Story(
    isClose: false,
    timeFrom: "10m",
    user: users[Random().nextInt(users.length)],
    viewed: false,
  ),
];

List<String> feedImages = [
  "assets/images/feed1.jpg",
  "assets/images/feed2.jpg",
  "assets/images/feed3.jpg",
  "assets/images/feed4.jpg",
  "assets/images/feed5.jpg",
  "assets/images/feed6.jpg",
  "assets/images/feed7.jpg",
  "assets/images/feed8.jpg",
  "assets/images/feed9.jpg",
  "assets/images/feed10.jpg",
  "assets/images/feed11.jpg",
  "assets/images/feed12.jpg",
  "assets/images/feed13.jpg",
  "assets/images/feed14.jpg",
  "assets/images/feed15.jpg",
  "assets/images/feed16.jpg",
  "assets/images/feed17.jpg",
  "assets/images/feed18.jpg",
  "assets/images/feed19.jpg",
  "assets/images/feed20.jpg",
  "assets/images/feed21.jpg",
  "assets/images/feed22.jpg",
];
List<String> storyImages = [
  "assets/images/story1.jpg",
  "assets/images/story2.jpg",
  "assets/images/story3.jpg",
  "assets/images/story4.jpg",
  "assets/images/story5.jpg",
  "assets/images/story6.jpg",
  "assets/images/story7.jpg",
  "assets/images/story8.jpg",
  "assets/images/story9.jpg",
  "assets/images/story10.jpg",
  "assets/images/story11.jpg",
  "assets/images/story12.jpg",
  "assets/images/story13.jpg",
  "assets/images/story14.jpg",
  "assets/images/story15.jpg",
  "assets/images/story16.jpg",
  "assets/images/story17.jpg",
  "assets/images/story18.jpg",
  "assets/images/story19.jpg",
  "assets/images/story20.jpg",
  "assets/images/story21.jpg",
  "assets/images/story22.jpg",
  "assets/images/story23.jpg",
  "assets/images/story24.jpg",
  "assets/images/story25.jpg",
  "assets/images/story26.jpg",
  "assets/images/story27.jpg",
  "assets/images/story28.jpg",
  "assets/images/story29.jpg",
];

List<Post> feed = [
  ...List.generate(
    30,
    (index) => Post(
      user: users[Random().nextInt(users.length)],
      likeCount: Random().nextInt(10000),
      commentsCount: Random().nextInt(10000),
      isLiked: Random().nextBool(),
      isSaved: Random().nextBool(),
      fromTime: Random().nextInt(50).toString(),
      location: "Asgard",
      postDesc: "Really ? c'mon",
      postImage: feedImages[Random().nextInt(feedImages.length)],
    ),
  ),
];

List<String> likeAvatars = [
  ...List.generate(
      3, (index) => storyImages[Random().nextInt(storyImages.length)])
];
